### ISSUE TITLE
remove conda-forge recipe from the organization

### ISSUE THREAD

**Issue by 12rambau** [gee-community/gee-community.github.io#6]
based on the content of the recipe folder, I assume it was used at some point to create the conda-forge earthengine-api feedstock but now that it's up and running this repository should be deleted. 

https://github.com/gee-community/staged-recipes

**Comment by 12rambau** [comment]
@tylere if not removing at least archive it with a meaningful message ?

**Comment by tylere** [comment]
Was this issue filed in the wrong repo? (i.e. there isn't a recipe folder in this repo.)

**Comment by 12rambau** [comment]
It's just that I asked community question in this one. Let me move it to the recipe repo

**Comment by tylere** [comment]
Thanks for bringing this up. I have deleted the outdated repo.
